name: examples
description: A pure client-side app without ssr.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.9.2
  dart_gsap:
    path: ../dartgsap
  jaspr_router: ^0.3.0
dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
  lints: ^2.1.0

jaspr:
  uses-ssr: false
